services:
  ors-app:
    build:
      context: ./
    container_name: ors-app
    ports:
      - "8080:8082"  
      - "9001:9001"  
    image: openrouteservice/openrouteservice:latest
    volumes: 
      - ./ors-docker:/home/ors  
      - ./bolivia-latest.osm.pbf:/home/ors/files/osm.file.pbf 
    environment:
      REBUILD_GRAPHS: False 
      CONTAINER_LOG_LEVEL: INFO  
      XMS: 1g  
      XMX: 2g  
      ADDITIONAL_JAVA_OPTS: "" 